CREATE TABLE cats (
	id INTEGER PRIMARY KEY,
	name VARCHAR(255),
	age INTEGER,
	is_vaccinated TINYINT,
	owner INTEGER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (owner) REFERENCES users (id)
	      ON DELETE SET NULL
	      ON UPDATE SET NULL
);