INSERT INTO cats
(name, age, is_vaccinated, owner, created_at, updated_at)
VALUES('Simon', 4, 0, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), 
('Barsik', 1, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Liza', 3, 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Boss', 10, 0, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
